### PR TITLE
Adds Style.unsafeWithProp

### LINKED ISSUE #65: Expose a unsafeAddProp to ReactDOMRe.Style
https://github.com/reasonml/reason-react/pull/45#issuecomment-280968366

### PR DESCRIPTION
**Pull request by glennsl**
Fixes #65 

I named it unsafeWithProp to emphasize that it's immutable. Also removed the `%raw` from `Style.combine` by sprinkling a bit of `magic` on it.

### CODE REVIEW

**Comment by glennsl** [comment]
Also, this might be a good time to add some tests... ?

**Comment by glennsl** [comment]
So... how about this, then? ;)

(Shoot, looks like you decided to eventually go to sleep after all. I was trying catch you off guard!)

**Comment by chenglou** [comment]
I forgot about this issue (again)...
Well, now that we've moved over to the new repo, I'll copy paste your changes into it! Thanks again

**Comment by glennsl** [comment]
lol, I had lost all hope! :laughing:

**Pull request closed without merging**
