### PR TITLE
Replace List.find with List.filter

### PR DESCRIPTION
**Pull request by SanderSpies**
#5 

Removes try catch in generated JS.

### CODE REVIEW

**Comment by bobzhang** [comment]
List.length > 0 is expensive, better to be is_empty

**Comment by chenglou** [comment]
This won't stop at the first item though? Also, try catch doesn't trigger deopt in JS engines anymore afaik? @jordwalke

**Comment by jordwalke** [comment]
I've seen warnings in the chrome profiler very recently telling me that try/catch prevented optimizations.

**Comment by chenglou** [comment]
Ok well that's that. Can we have a version that stops after the first item?

As an aside, if someone allocates a function inline in the jsx with `onClick=(updater (fun ...))` then this list grows at each refresh. Not sure what to do. Maybe cap this list in the future (or use ppx to prevent this lol, `onClick=([%updater functionReference])`).

**Comment by SanderSpies** [comment]
@chenglou it does pick the first item in the if block with `List.nth`.

**Comment by chenglou** [comment]
Yeah I meant stop at the first occurrence rather than filtering over the whole thing. I'm gonna merge this but let's continue the discussion, if any. Thanks!

**Pull request merged**
